export enum fileError {
    LIMIT_PART_COUNT = 429,
    LIMIT_FILE_SIZE = 413,
    LIMIT_FILE_COUNT = 429,
    LIMIT_FIELD_KEY = 413,
    LIMIT_FIELD_VALUE = 413,
    LIMIT_FIELD_COUNT = 413,
    LIMIT_UNEXPECTED_FILE = 400
}
