#!/bin/bash
cd $1
mkdir -p ./dist/logs ./dist/migration/dump ./dist/uploads/documents/xs ./dist/uploads/documents/md ./dist/uploads/documents/xl
echo "Installing Bcrypt"
npm i bcrypt --save 
echo "Installing TypeScript globally"
npm i typescript -g 
echo "Installing TypeOrm globally"
npm i typeorm -g 
echo "Installing Depedencies"
npm i 
echo "Compiling TypeScript into JavaScript"
./node_modules/.bin/tsc --noEmit
echo "Done"
